// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class newachivement
{
        public const string achievement_collect_50_coins_in_1_run = "CgkIyLm0hvgNEAIQAg"; // <GPGSID>
        public const string achievement_collect_600_points_in_1_run = "CgkIyLm0hvgNEAIQBQ"; // <GPGSID>
        public const string achievement_collect_a_total_of_5000_points = "CgkIyLm0hvgNEAIQCw"; // <GPGSID>
        public const string achievement_collect_100_coins_in_1_run = "CgkIyLm0hvgNEAIQAw"; // <GPGSID>
        public const string leaderboard_coin_collected = "CgkIyLm0hvgNEAIQCg"; // <GPGSID>
        public const string achievement_collect_a_total_of_10000_points = "CgkIyLm0hvgNEAIQCA"; // <GPGSID>
        public const string achievement_collect_1200_points_in_1_run = "CgkIyLm0hvgNEAIQAQ"; // <GPGSID>
        public const string achievement_collect_10_coins_in_1_run = "CgkIyLm0hvgNEAIQCQ"; // <GPGSID>
        public const string achievement_collect_300_points_in_1_run = "CgkIyLm0hvgNEAIQBA"; // <GPGSID>
        public const string leaderboard_score = "CgkIyLm0hvgNEAIQBg"; // <GPGSID>

}

